// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module FFT_fft_stage (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        in_i_address0,
        in_i_ce0,
        in_i_q0,
        in_i_address1,
        in_i_ce1,
        in_i_q1,
        out_r_0_address0,
        out_r_0_ce0,
        out_r_0_we0,
        out_r_0_d0,
        out_r_0_address1,
        out_r_0_ce1,
        out_r_0_we1,
        out_r_0_d1,
        out_r_1_address0,
        out_r_1_ce0,
        out_r_1_we0,
        out_r_1_d0,
        out_r_2_address0,
        out_r_2_ce0,
        out_r_2_we0,
        out_r_2_d0,
        out_r_3_address0,
        out_r_3_ce0,
        out_r_3_we0,
        out_r_3_d0,
        out_i_0_address0,
        out_i_0_ce0,
        out_i_0_we0,
        out_i_0_d0,
        out_i_0_address1,
        out_i_0_ce1,
        out_i_0_we1,
        out_i_0_d1,
        out_i_1_address0,
        out_i_1_ce0,
        out_i_1_we0,
        out_i_1_d0,
        out_i_2_address0,
        out_i_2_ce0,
        out_i_2_we0,
        out_i_2_d0,
        out_i_3_address0,
        out_i_3_ce0,
        out_i_3_we0,
        out_i_3_d0,
        grp_fu_186_p_din0,
        grp_fu_186_p_din1,
        grp_fu_186_p_opcode,
        grp_fu_186_p_dout0,
        grp_fu_186_p_ce,
        grp_fu_190_p_din0,
        grp_fu_190_p_din1,
        grp_fu_190_p_opcode,
        grp_fu_190_p_dout0,
        grp_fu_190_p_ce,
        grp_fu_194_p_din0,
        grp_fu_194_p_din1,
        grp_fu_194_p_opcode,
        grp_fu_194_p_dout0,
        grp_fu_194_p_ce,
        grp_fu_198_p_din0,
        grp_fu_198_p_din1,
        grp_fu_198_p_opcode,
        grp_fu_198_p_dout0,
        grp_fu_198_p_ce,
        grp_fu_202_p_din0,
        grp_fu_202_p_din1,
        grp_fu_202_p_opcode,
        grp_fu_202_p_dout0,
        grp_fu_202_p_ce,
        grp_fu_206_p_din0,
        grp_fu_206_p_din1,
        grp_fu_206_p_opcode,
        grp_fu_206_p_dout0,
        grp_fu_206_p_ce,
        grp_fu_210_p_din0,
        grp_fu_210_p_din1,
        grp_fu_210_p_dout0,
        grp_fu_210_p_ce,
        grp_fu_214_p_din0,
        grp_fu_214_p_din1,
        grp_fu_214_p_dout0,
        grp_fu_214_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] in_r_address0;
output   in_r_ce0;
input  [63:0] in_r_q0;
output  [8:0] in_r_address1;
output   in_r_ce1;
input  [63:0] in_r_q1;
output  [8:0] in_i_address0;
output   in_i_ce0;
input  [63:0] in_i_q0;
output  [8:0] in_i_address1;
output   in_i_ce1;
input  [63:0] in_i_q1;
output  [6:0] out_r_0_address0;
output   out_r_0_ce0;
output   out_r_0_we0;
output  [63:0] out_r_0_d0;
output  [6:0] out_r_0_address1;
output   out_r_0_ce1;
output   out_r_0_we1;
output  [63:0] out_r_0_d1;
output  [6:0] out_r_1_address0;
output   out_r_1_ce0;
output   out_r_1_we0;
output  [63:0] out_r_1_d0;
output  [6:0] out_r_2_address0;
output   out_r_2_ce0;
output   out_r_2_we0;
output  [63:0] out_r_2_d0;
output  [6:0] out_r_3_address0;
output   out_r_3_ce0;
output   out_r_3_we0;
output  [63:0] out_r_3_d0;
output  [6:0] out_i_0_address0;
output   out_i_0_ce0;
output   out_i_0_we0;
output  [63:0] out_i_0_d0;
output  [6:0] out_i_0_address1;
output   out_i_0_ce1;
output   out_i_0_we1;
output  [63:0] out_i_0_d1;
output  [6:0] out_i_1_address0;
output   out_i_1_ce0;
output   out_i_1_we0;
output  [63:0] out_i_1_d0;
output  [6:0] out_i_2_address0;
output   out_i_2_ce0;
output   out_i_2_we0;
output  [63:0] out_i_2_d0;
output  [6:0] out_i_3_address0;
output   out_i_3_ce0;
output   out_i_3_we0;
output  [63:0] out_i_3_d0;
output  [63:0] grp_fu_186_p_din0;
output  [63:0] grp_fu_186_p_din1;
output  [1:0] grp_fu_186_p_opcode;
input  [63:0] grp_fu_186_p_dout0;
output   grp_fu_186_p_ce;
output  [63:0] grp_fu_190_p_din0;
output  [63:0] grp_fu_190_p_din1;
output  [1:0] grp_fu_190_p_opcode;
input  [63:0] grp_fu_190_p_dout0;
output   grp_fu_190_p_ce;
output  [63:0] grp_fu_194_p_din0;
output  [63:0] grp_fu_194_p_din1;
output  [1:0] grp_fu_194_p_opcode;
input  [63:0] grp_fu_194_p_dout0;
output   grp_fu_194_p_ce;
output  [63:0] grp_fu_198_p_din0;
output  [63:0] grp_fu_198_p_din1;
output  [1:0] grp_fu_198_p_opcode;
input  [63:0] grp_fu_198_p_dout0;
output   grp_fu_198_p_ce;
output  [63:0] grp_fu_202_p_din0;
output  [63:0] grp_fu_202_p_din1;
output  [1:0] grp_fu_202_p_opcode;
input  [63:0] grp_fu_202_p_dout0;
output   grp_fu_202_p_ce;
output  [63:0] grp_fu_206_p_din0;
output  [63:0] grp_fu_206_p_din1;
output  [1:0] grp_fu_206_p_opcode;
input  [63:0] grp_fu_206_p_dout0;
output   grp_fu_206_p_ce;
output  [63:0] grp_fu_210_p_din0;
output  [63:0] grp_fu_210_p_din1;
input  [63:0] grp_fu_210_p_dout0;
output   grp_fu_210_p_ce;
output  [63:0] grp_fu_214_p_din0;
output  [63:0] grp_fu_214_p_din1;
input  [63:0] grp_fu_214_p_dout0;
output   grp_fu_214_p_ce;

reg ap_idle;
reg[8:0] in_r_address0;
reg in_r_ce0;
reg[8:0] in_r_address1;
reg in_r_ce1;
reg[8:0] in_i_address0;
reg in_i_ce0;
reg[8:0] in_i_address1;
reg in_i_ce1;
reg out_r_0_ce0;
reg out_r_0_we0;
reg out_r_0_ce1;
reg out_r_0_we1;
reg[6:0] out_r_1_address0;
reg out_r_1_ce0;
reg out_r_1_we0;
reg[63:0] out_r_1_d0;
reg[6:0] out_r_2_address0;
reg out_r_2_ce0;
reg out_r_2_we0;
reg[63:0] out_r_2_d0;
reg[6:0] out_r_3_address0;
reg out_r_3_ce0;
reg out_r_3_we0;
reg[63:0] out_r_3_d0;
reg out_i_0_ce0;
reg out_i_0_we0;
reg out_i_0_ce1;
reg out_i_0_we1;
reg[6:0] out_i_1_address0;
reg out_i_1_ce0;
reg out_i_1_we0;
reg[63:0] out_i_1_d0;
reg[6:0] out_i_2_address0;
reg out_i_2_ce0;
reg out_i_2_we0;
reg[63:0] out_i_2_d0;
reg[6:0] out_i_3_address0;
reg out_i_3_ce0;
reg out_i_3_we0;
reg[63:0] out_i_3_d0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state8_pp0_stage3_iter1;
wire    ap_block_state12_pp0_stage3_iter2;
wire    ap_block_state16_pp0_stage3_iter3;
wire    ap_block_state20_pp0_stage3_iter4;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] tmp_reg_681;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [63:0] reg_440;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state13_pp0_stage0_iter3;
wire    ap_block_state17_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_state10_pp0_stage1_iter2;
wire    ap_block_state14_pp0_stage1_iter3;
wire    ap_block_state18_pp0_stage1_iter4;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state7_pp0_stage2_iter1;
wire    ap_block_state11_pp0_stage2_iter2;
wire    ap_block_state15_pp0_stage2_iter3;
wire    ap_block_state19_pp0_stage2_iter4;
wire    ap_block_pp0_stage2_11001;
reg   [63:0] reg_447;
wire   [0:0] tmp_fu_462_p3;
wire   [7:0] i_fu_470_p1;
reg   [7:0] i_reg_685;
reg   [5:0] lshr_ln_reg_692;
reg   [5:0] lshr_ln_reg_692_pp0_iter1_reg;
reg   [5:0] lshr_ln_reg_692_pp0_iter2_reg;
reg   [5:0] lshr_ln_reg_692_pp0_iter3_reg;
reg   [5:0] lshr_ln_reg_692_pp0_iter4_reg;
wire   [7:0] i_7_fu_484_p2;
reg   [7:0] i_7_reg_698;
reg   [5:0] tmp_1_reg_713;
reg   [5:0] tmp_1_reg_713_pp0_iter1_reg;
reg   [5:0] tmp_1_reg_713_pp0_iter2_reg;
reg   [5:0] tmp_1_reg_713_pp0_iter3_reg;
reg   [5:0] tmp_1_reg_713_pp0_iter4_reg;
wire   [7:0] i_8_fu_514_p2;
reg   [7:0] i_8_reg_718;
reg   [5:0] tmp_2_reg_733;
reg   [5:0] tmp_2_reg_733_pp0_iter1_reg;
reg   [5:0] tmp_2_reg_733_pp0_iter2_reg;
reg   [5:0] tmp_2_reg_733_pp0_iter3_reg;
reg   [5:0] tmp_2_reg_733_pp0_iter4_reg;
reg   [63:0] tmp_re_7_reg_748;
reg   [63:0] tmp_im_7_reg_753;
reg   [63:0] tmp_re_8_reg_758;
reg   [63:0] tmp_im_8_reg_763;
wire   [7:0] i_9_fu_568_p2;
reg   [7:0] i_9_reg_768;
reg   [5:0] tmp_3_reg_783;
reg   [5:0] tmp_3_reg_783_pp0_iter1_reg;
reg   [5:0] tmp_3_reg_783_pp0_iter2_reg;
reg   [5:0] tmp_3_reg_783_pp0_iter3_reg;
reg   [5:0] tmp_3_reg_783_pp0_iter4_reg;
reg   [63:0] tmp_re_reg_788;
reg   [63:0] tmp_im_reg_793;
reg   [63:0] tmp_re_9_reg_818;
reg   [63:0] tmp_im_9_reg_823;
wire    ap_block_pp0_stage3_11001;
reg   [63:0] x_re_7_reg_838;
reg   [63:0] x_re_7_reg_838_pp0_iter1_reg;
reg   [63:0] x_re_7_reg_838_pp0_iter2_reg;
reg   [63:0] x_im_7_reg_844;
reg   [63:0] x_im_7_reg_844_pp0_iter1_reg;
reg   [63:0] x_im_7_reg_844_pp0_iter2_reg;
reg   [63:0] x_re_8_reg_850;
reg   [63:0] x_re_8_reg_850_pp0_iter1_reg;
reg   [63:0] x_re_8_reg_850_pp0_iter2_reg;
reg   [63:0] x_im_8_reg_856;
reg   [63:0] x_im_8_reg_856_pp0_iter1_reg;
reg   [63:0] x_im_8_reg_856_pp0_iter2_reg;
reg   [63:0] x_re_reg_872;
reg   [63:0] x_re_reg_872_pp0_iter2_reg;
reg   [63:0] x_re_reg_872_pp0_iter3_reg;
reg   [63:0] x_im_reg_878;
reg   [63:0] x_im_reg_878_pp0_iter2_reg;
reg   [63:0] x_im_reg_878_pp0_iter3_reg;
reg   [63:0] x_re_9_reg_884;
reg   [63:0] x_re_9_reg_884_pp0_iter2_reg;
reg   [63:0] x_re_9_reg_884_pp0_iter3_reg;
reg   [63:0] x_im_9_reg_890;
reg   [63:0] x_im_9_reg_890_pp0_iter2_reg;
reg   [63:0] x_im_9_reg_890_pp0_iter3_reg;
reg   [63:0] mul33_1_reg_896;
reg   [63:0] mul34_1_reg_902;
reg   [63:0] mul33_2_reg_908;
reg   [63:0] mul34_2_reg_914;
reg   [63:0] mul33_3_reg_920;
reg   [63:0] mul34_3_reg_926;
reg   [63:0] mul_reg_932;
reg   [63:0] mul7_reg_938;
reg   [63:0] y_re_7_reg_944;
reg   [63:0] y_im_7_reg_950;
reg   [63:0] y_re_8_reg_956;
reg   [63:0] y_im_8_reg_962;
reg   [63:0] y_re_9_reg_968;
reg   [63:0] y_im_9_reg_974;
reg   [63:0] y_re_reg_980;
reg   [63:0] y_im_reg_986;
wire   [63:0] zext_ln94_fu_617_p1;
reg   [63:0] zext_ln94_reg_992;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln88_7_fu_498_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln88_8_fu_528_p1;
wire   [63:0] zext_ln88_fu_562_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln88_9_fu_581_p1;
wire   [63:0] zext_ln86_10_fu_597_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln86_11_fu_602_p1;
wire   [63:0] zext_ln86_fu_607_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln86_12_fu_612_p1;
wire   [63:0] zext_ln97_1_fu_629_p1;
wire   [63:0] zext_ln97_2_fu_642_p1;
wire   [63:0] zext_ln97_fu_655_p1;
wire   [63:0] zext_ln97_3_fu_668_p1;
reg   [8:0] n_01_fu_70;
wire   [8:0] n_fu_544_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_n_9;
reg   [63:0] grp_fu_396_p0;
reg   [63:0] grp_fu_396_p1;
reg   [63:0] grp_fu_400_p0;
reg   [63:0] grp_fu_400_p1;
reg   [63:0] grp_fu_404_p0;
reg   [63:0] grp_fu_404_p1;
reg   [63:0] grp_fu_409_p0;
reg   [63:0] grp_fu_409_p1;
reg   [63:0] grp_fu_414_p0;
reg   [63:0] grp_fu_414_p1;
reg   [63:0] grp_fu_418_p0;
reg   [63:0] grp_fu_418_p1;
reg   [63:0] grp_fu_430_p0;
reg   [63:0] grp_fu_435_p0;
wire   [8:0] zext_ln88_7_cast_fu_490_p3;
wire   [8:0] zext_ln88_8_cast_fu_520_p3;
wire   [8:0] zext_ln88_cast_fu_555_p3;
wire   [8:0] zext_ln88_9_cast_fu_573_p3;
wire   [6:0] zext_ln97_1_cast_fu_622_p3;
wire   [6:0] zext_ln97_2_cast_fu_635_p3;
wire   [6:0] zext_ln97_cast_fu_648_p3;
wire   [6:0] zext_ln97_3_cast_fu_661_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0;
wire    ap_enable_operation_227;
reg    ap_enable_state17_pp0_iter4_stage0;
wire    ap_enable_operation_248;
reg    ap_enable_state18_pp0_iter4_stage1;
wire    ap_enable_operation_230;
wire    ap_enable_operation_250;
wire    ap_enable_operation_253;
wire    ap_enable_operation_270;
reg    ap_enable_state19_pp0_iter4_stage2;
wire    ap_enable_operation_256;
wire    ap_enable_operation_272;
wire    ap_enable_operation_275;
wire    ap_enable_operation_300;
reg    ap_enable_state20_pp0_iter4_stage3;
wire    ap_enable_operation_278;
wire    ap_enable_operation_302;
wire    ap_enable_operation_285;
wire    ap_enable_operation_293;
wire    ap_enable_operation_288;
wire    ap_enable_operation_296;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

FFT_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (tmp_fu_462_p3 == 1'd0))) begin
            n_01_fu_70 <= n_fu_544_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_01_fu_70 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        x_im_7_reg_844_pp0_iter1_reg <= x_im_7_reg_844;
        x_im_7_reg_844_pp0_iter2_reg <= x_im_7_reg_844_pp0_iter1_reg;
        x_im_8_reg_856_pp0_iter1_reg <= x_im_8_reg_856;
        x_im_8_reg_856_pp0_iter2_reg <= x_im_8_reg_856_pp0_iter1_reg;
        x_re_7_reg_838_pp0_iter1_reg <= x_re_7_reg_838;
        x_re_7_reg_838_pp0_iter2_reg <= x_re_7_reg_838_pp0_iter1_reg;
        x_re_8_reg_850_pp0_iter1_reg <= x_re_8_reg_850;
        x_re_8_reg_850_pp0_iter2_reg <= x_re_8_reg_850_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_fu_462_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_7_reg_698[7 : 1] <= i_7_fu_484_p2[7 : 1];
        i_8_reg_718[0] <= i_8_fu_514_p2[0];
i_8_reg_718[7 : 2] <= i_8_fu_514_p2[7 : 2];
        i_reg_685 <= i_fu_470_p1;
        lshr_ln_reg_692 <= {{ap_sig_allocacmp_n_9[7:2]}};
        tmp_1_reg_713 <= {{i_7_fu_484_p2[7:2]}};
        tmp_2_reg_733 <= {{i_8_fu_514_p2[7:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_681 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i_9_reg_768[7 : 2] <= i_9_fu_568_p2[7 : 2];
        tmp_3_reg_783 <= {{i_9_fu_568_p2[7:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_692_pp0_iter1_reg <= lshr_ln_reg_692;
        lshr_ln_reg_692_pp0_iter2_reg <= lshr_ln_reg_692_pp0_iter1_reg;
        lshr_ln_reg_692_pp0_iter3_reg <= lshr_ln_reg_692_pp0_iter2_reg;
        lshr_ln_reg_692_pp0_iter4_reg <= lshr_ln_reg_692_pp0_iter3_reg;
        tmp_1_reg_713_pp0_iter1_reg <= tmp_1_reg_713;
        tmp_1_reg_713_pp0_iter2_reg <= tmp_1_reg_713_pp0_iter1_reg;
        tmp_1_reg_713_pp0_iter3_reg <= tmp_1_reg_713_pp0_iter2_reg;
        tmp_1_reg_713_pp0_iter4_reg <= tmp_1_reg_713_pp0_iter3_reg;
        tmp_2_reg_733_pp0_iter1_reg <= tmp_2_reg_733;
        tmp_2_reg_733_pp0_iter2_reg <= tmp_2_reg_733_pp0_iter1_reg;
        tmp_2_reg_733_pp0_iter3_reg <= tmp_2_reg_733_pp0_iter2_reg;
        tmp_2_reg_733_pp0_iter4_reg <= tmp_2_reg_733_pp0_iter3_reg;
        tmp_reg_681 <= ap_sig_allocacmp_n_9[32'd8];
        x_im_9_reg_890_pp0_iter2_reg <= x_im_9_reg_890;
        x_im_9_reg_890_pp0_iter3_reg <= x_im_9_reg_890_pp0_iter2_reg;
        x_im_reg_878_pp0_iter2_reg <= x_im_reg_878;
        x_im_reg_878_pp0_iter3_reg <= x_im_reg_878_pp0_iter2_reg;
        x_re_9_reg_884_pp0_iter2_reg <= x_re_9_reg_884;
        x_re_9_reg_884_pp0_iter3_reg <= x_re_9_reg_884_pp0_iter2_reg;
        x_re_reg_872_pp0_iter2_reg <= x_re_reg_872;
        x_re_reg_872_pp0_iter3_reg <= x_re_reg_872_pp0_iter2_reg;
        zext_ln94_reg_992[5 : 0] <= zext_ln94_fu_617_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul33_1_reg_896 <= grp_fu_210_p_dout0;
        mul34_1_reg_902 <= grp_fu_214_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul33_2_reg_908 <= grp_fu_210_p_dout0;
        mul34_2_reg_914 <= grp_fu_214_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul33_3_reg_920 <= grp_fu_210_p_dout0;
        mul34_3_reg_926 <= grp_fu_214_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul7_reg_938 <= grp_fu_214_p_dout0;
        mul_reg_932 <= grp_fu_210_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_440 <= grp_fu_202_p_dout0;
        reg_447 <= grp_fu_206_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_3_reg_783_pp0_iter1_reg <= tmp_3_reg_783;
        tmp_3_reg_783_pp0_iter2_reg <= tmp_3_reg_783_pp0_iter1_reg;
        tmp_3_reg_783_pp0_iter3_reg <= tmp_3_reg_783_pp0_iter2_reg;
        tmp_3_reg_783_pp0_iter4_reg <= tmp_3_reg_783_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_681 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_im_7_reg_753 <= in_i_q1;
        tmp_im_8_reg_763 <= in_i_q0;
        tmp_re_7_reg_748 <= in_r_q1;
        tmp_re_8_reg_758 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_681 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        tmp_im_9_reg_823 <= in_i_q0;
        tmp_im_reg_793 <= in_i_q1;
        tmp_re_9_reg_818 <= in_r_q0;
        tmp_re_reg_788 <= in_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_681 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        x_im_7_reg_844 <= in_i_q1;
        x_im_8_reg_856 <= in_i_q0;
        x_re_7_reg_838 <= in_r_q1;
        x_re_8_reg_850 <= in_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_im_9_reg_890 <= in_i_q0;
        x_im_reg_878 <= in_i_q1;
        x_re_9_reg_884 <= in_r_q0;
        x_re_reg_872 <= in_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        y_im_7_reg_950 <= grp_fu_190_p_dout0;
        y_re_7_reg_944 <= grp_fu_186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_im_8_reg_962 <= grp_fu_190_p_dout0;
        y_re_8_reg_956 <= grp_fu_186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        y_im_9_reg_974 <= grp_fu_190_p_dout0;
        y_re_9_reg_968 <= grp_fu_186_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        y_im_reg_986 <= grp_fu_190_p_dout0;
        y_re_reg_980 <= grp_fu_186_p_dout0;
    end
end

always @ (*) begin
    if (((tmp_reg_681 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_9 = 9'd0;
    end else begin
        ap_sig_allocacmp_n_9 = n_01_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_396_p0 = mul_reg_932;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_396_p0 = mul33_3_reg_920;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_396_p0 = mul33_2_reg_908;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_396_p0 = mul33_1_reg_896;
    end else begin
        grp_fu_396_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_396_p1 = mul7_reg_938;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_396_p1 = mul34_3_reg_926;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_396_p1 = mul34_2_reg_914;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_396_p1 = mul34_1_reg_902;
    end else begin
        grp_fu_396_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_400_p0 = mul_reg_932;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_400_p0 = mul33_3_reg_920;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_400_p0 = mul33_2_reg_908;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_400_p0 = mul33_1_reg_896;
    end else begin
        grp_fu_400_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_400_p1 = mul7_reg_938;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_400_p1 = mul34_3_reg_926;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_400_p1 = mul34_2_reg_914;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_400_p1 = mul34_1_reg_902;
    end else begin
        grp_fu_400_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_404_p0 = x_re_reg_872_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_404_p0 = x_re_9_reg_884_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_404_p0 = x_re_8_reg_850_pp0_iter2_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_404_p0 = x_re_7_reg_838_pp0_iter2_reg;
        end else begin
            grp_fu_404_p0 = 'bx;
        end
    end else begin
        grp_fu_404_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_404_p1 = y_re_reg_980;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_404_p1 = y_re_9_reg_968;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_404_p1 = y_re_8_reg_956;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_404_p1 = y_re_7_reg_944;
        end else begin
            grp_fu_404_p1 = 'bx;
        end
    end else begin
        grp_fu_404_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_409_p0 = x_im_reg_878_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_409_p0 = x_im_9_reg_890_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_409_p0 = x_im_8_reg_856_pp0_iter2_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_409_p0 = x_im_7_reg_844_pp0_iter2_reg;
        end else begin
            grp_fu_409_p0 = 'bx;
        end
    end else begin
        grp_fu_409_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_409_p1 = y_im_reg_986;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_409_p1 = y_im_9_reg_974;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_409_p1 = y_im_8_reg_962;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_409_p1 = y_im_7_reg_950;
        end else begin
            grp_fu_409_p1 = 'bx;
        end
    end else begin
        grp_fu_409_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_414_p0 = x_re_reg_872_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_414_p0 = x_re_9_reg_884_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_414_p0 = x_re_8_reg_850_pp0_iter2_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_414_p0 = x_re_7_reg_838_pp0_iter2_reg;
        end else begin
            grp_fu_414_p0 = 'bx;
        end
    end else begin
        grp_fu_414_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_414_p1 = y_re_reg_980;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_414_p1 = y_re_9_reg_968;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_414_p1 = y_re_8_reg_956;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_414_p1 = y_re_7_reg_944;
        end else begin
            grp_fu_414_p1 = 'bx;
        end
    end else begin
        grp_fu_414_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_418_p0 = x_im_reg_878_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_418_p0 = x_im_9_reg_890_pp0_iter3_reg;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_418_p0 = x_im_8_reg_856_pp0_iter2_reg;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_418_p0 = x_im_7_reg_844_pp0_iter2_reg;
        end else begin
            grp_fu_418_p0 = 'bx;
        end
    end else begin
        grp_fu_418_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_418_p1 = y_im_reg_986;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_418_p1 = y_im_9_reg_974;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_418_p1 = y_im_8_reg_962;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_418_p1 = y_im_7_reg_950;
        end else begin
            grp_fu_418_p1 = 'bx;
        end
    end else begin
        grp_fu_418_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_430_p0 = tmp_re_reg_788;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_430_p0 = tmp_re_9_reg_818;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_430_p0 = tmp_re_8_reg_758;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_430_p0 = tmp_re_7_reg_748;
    end else begin
        grp_fu_430_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_435_p0 = tmp_im_reg_793;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_435_p0 = tmp_im_9_reg_823;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_435_p0 = tmp_im_8_reg_763;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_435_p0 = tmp_im_7_reg_753;
    end else begin
        grp_fu_435_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            in_i_address0 = zext_ln86_12_fu_612_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_i_address0 = zext_ln86_11_fu_602_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_i_address0 = zext_ln88_9_fu_581_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            in_i_address0 = zext_ln88_8_fu_528_p1;
        end else begin
            in_i_address0 = 'bx;
        end
    end else begin
        in_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            in_i_address1 = zext_ln86_fu_607_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_i_address1 = zext_ln86_10_fu_597_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_i_address1 = zext_ln88_fu_562_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            in_i_address1 = zext_ln88_7_fu_498_p1;
        end else begin
            in_i_address1 = 'bx;
        end
    end else begin
        in_i_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_i_ce0 = 1'b1;
    end else begin
        in_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_i_ce1 = 1'b1;
    end else begin
        in_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            in_r_address0 = zext_ln86_12_fu_612_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_r_address0 = zext_ln86_11_fu_602_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_r_address0 = zext_ln88_9_fu_581_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            in_r_address0 = zext_ln88_8_fu_528_p1;
        end else begin
            in_r_address0 = 'bx;
        end
    end else begin
        in_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            in_r_address1 = zext_ln86_fu_607_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            in_r_address1 = zext_ln86_10_fu_597_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            in_r_address1 = zext_ln88_fu_562_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            in_r_address1 = zext_ln88_7_fu_498_p1;
        end else begin
            in_r_address1 = 'bx;
        end
    end else begin
        in_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in_r_ce1 = 1'b1;
    end else begin
        in_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_i_0_ce0 = 1'b1;
    end else begin
        out_i_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_i_0_ce1 = 1'b1;
    end else begin
        out_i_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_i_0_we0 = 1'b1;
    end else begin
        out_i_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_i_0_we1 = 1'b1;
    end else begin
        out_i_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_i_1_address0 = zext_ln97_1_fu_629_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_i_1_address0 = zext_ln94_fu_617_p1;
        end else begin
            out_i_1_address0 = 'bx;
        end
    end else begin
        out_i_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_i_1_ce0 = 1'b1;
    end else begin
        out_i_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_i_1_d0 = reg_447;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_i_1_d0 = grp_fu_198_p_dout0;
        end else begin
            out_i_1_d0 = 'bx;
        end
    end else begin
        out_i_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_i_1_we0 = 1'b1;
    end else begin
        out_i_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_i_2_address0 = zext_ln97_2_fu_642_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_i_2_address0 = zext_ln94_reg_992;
        end else begin
            out_i_2_address0 = 'bx;
        end
    end else begin
        out_i_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_i_2_ce0 = 1'b1;
    end else begin
        out_i_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_i_2_d0 = reg_447;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_i_2_d0 = grp_fu_198_p_dout0;
        end else begin
            out_i_2_d0 = 'bx;
        end
    end else begin
        out_i_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_i_2_we0 = 1'b1;
    end else begin
        out_i_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            out_i_3_address0 = zext_ln97_3_fu_668_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_i_3_address0 = zext_ln94_reg_992;
        end else begin
            out_i_3_address0 = 'bx;
        end
    end else begin
        out_i_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        out_i_3_ce0 = 1'b1;
    end else begin
        out_i_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            out_i_3_d0 = reg_447;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_i_3_d0 = grp_fu_198_p_dout0;
        end else begin
            out_i_3_d0 = 'bx;
        end
    end else begin
        out_i_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        out_i_3_we0 = 1'b1;
    end else begin
        out_i_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_0_ce0 = 1'b1;
    end else begin
        out_r_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_0_ce1 = 1'b1;
    end else begin
        out_r_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_0_we0 = 1'b1;
    end else begin
        out_r_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_0_we1 = 1'b1;
    end else begin
        out_r_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_r_1_address0 = zext_ln97_1_fu_629_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_r_1_address0 = zext_ln94_fu_617_p1;
        end else begin
            out_r_1_address0 = 'bx;
        end
    end else begin
        out_r_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_1_ce0 = 1'b1;
    end else begin
        out_r_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_r_1_d0 = reg_440;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            out_r_1_d0 = grp_fu_194_p_dout0;
        end else begin
            out_r_1_d0 = 'bx;
        end
    end else begin
        out_r_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_1_we0 = 1'b1;
    end else begin
        out_r_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_r_2_address0 = zext_ln97_2_fu_642_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_r_2_address0 = zext_ln94_reg_992;
        end else begin
            out_r_2_address0 = 'bx;
        end
    end else begin
        out_r_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_r_2_ce0 = 1'b1;
    end else begin
        out_r_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_r_2_d0 = reg_440;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            out_r_2_d0 = grp_fu_194_p_dout0;
        end else begin
            out_r_2_d0 = 'bx;
        end
    end else begin
        out_r_2_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_r_2_we0 = 1'b1;
    end else begin
        out_r_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            out_r_3_address0 = zext_ln97_3_fu_668_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_r_3_address0 = zext_ln94_reg_992;
        end else begin
            out_r_3_address0 = 'bx;
        end
    end else begin
        out_r_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        out_r_3_ce0 = 1'b1;
    end else begin
        out_r_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter4 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            out_r_3_d0 = reg_440;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            out_r_3_d0 = grp_fu_194_p_dout0;
        end else begin
            out_r_3_d0 = 'bx;
        end
    end else begin
        out_r_3_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        out_r_3_we0 = 1'b1;
    end else begin
        out_r_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = (((ap_ST_fsm_pp0_stage3 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage3_subdone)) | ((ap_ST_fsm_pp0_stage2 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage2_subdone)) | ((ap_ST_fsm_pp0_stage1 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage1_subdone)) | ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone)));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_operation_227 = (1'b1 == 1'b1);

assign ap_enable_operation_230 = (1'b1 == 1'b1);

assign ap_enable_operation_248 = (1'b1 == 1'b1);

assign ap_enable_operation_250 = (1'b1 == 1'b1);

assign ap_enable_operation_253 = (1'b1 == 1'b1);

assign ap_enable_operation_256 = (1'b1 == 1'b1);

assign ap_enable_operation_270 = (1'b1 == 1'b1);

assign ap_enable_operation_272 = (1'b1 == 1'b1);

assign ap_enable_operation_275 = (1'b1 == 1'b1);

assign ap_enable_operation_278 = (1'b1 == 1'b1);

assign ap_enable_operation_285 = (1'b1 == 1'b1);

assign ap_enable_operation_288 = (1'b1 == 1'b1);

assign ap_enable_operation_293 = (1'b1 == 1'b1);

assign ap_enable_operation_296 = (1'b1 == 1'b1);

assign ap_enable_operation_300 = (1'b1 == 1'b1);

assign ap_enable_operation_302 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state17_pp0_iter4_stage0 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state18_pp0_iter4_stage1 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1));
end

always @ (*) begin
    ap_enable_state19_pp0_iter4_stage2 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2));
end

always @ (*) begin
    ap_enable_state20_pp0_iter4_stage3 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign grp_fu_186_p_ce = 1'b1;

assign grp_fu_186_p_din0 = grp_fu_396_p0;

assign grp_fu_186_p_din1 = grp_fu_396_p1;

assign grp_fu_186_p_opcode = 2'd1;

assign grp_fu_190_p_ce = 1'b1;

assign grp_fu_190_p_din0 = grp_fu_400_p0;

assign grp_fu_190_p_din1 = grp_fu_400_p1;

assign grp_fu_190_p_opcode = 2'd0;

assign grp_fu_194_p_ce = 1'b1;

assign grp_fu_194_p_din0 = grp_fu_404_p0;

assign grp_fu_194_p_din1 = grp_fu_404_p1;

assign grp_fu_194_p_opcode = 2'd0;

assign grp_fu_198_p_ce = 1'b1;

assign grp_fu_198_p_din0 = grp_fu_409_p0;

assign grp_fu_198_p_din1 = grp_fu_409_p1;

assign grp_fu_198_p_opcode = 2'd0;

assign grp_fu_202_p_ce = 1'b1;

assign grp_fu_202_p_din0 = grp_fu_414_p0;

assign grp_fu_202_p_din1 = grp_fu_414_p1;

assign grp_fu_202_p_opcode = 2'd1;

assign grp_fu_206_p_ce = 1'b1;

assign grp_fu_206_p_din0 = grp_fu_418_p0;

assign grp_fu_206_p_din1 = grp_fu_418_p1;

assign grp_fu_206_p_opcode = 2'd1;

assign grp_fu_210_p_ce = 1'b1;

assign grp_fu_210_p_din0 = grp_fu_430_p0;

assign grp_fu_210_p_din1 = 64'd4604544271217802189;

assign grp_fu_214_p_ce = 1'b1;

assign grp_fu_214_p_din0 = grp_fu_435_p0;

assign grp_fu_214_p_din1 = 64'd4604544271217802189;

assign i_7_fu_484_p2 = (i_fu_470_p1 | 8'd1);

assign i_8_fu_514_p2 = (i_fu_470_p1 | 8'd2);

assign i_9_fu_568_p2 = (i_reg_685 | 8'd3);

assign i_fu_470_p1 = ap_sig_allocacmp_n_9[7:0];

assign n_fu_544_p2 = (ap_sig_allocacmp_n_9 + 9'd4);

assign out_i_0_address0 = zext_ln97_fu_655_p1;

assign out_i_0_address1 = zext_ln94_reg_992;

assign out_i_0_d0 = grp_fu_206_p_dout0;

assign out_i_0_d1 = grp_fu_198_p_dout0;

assign out_r_0_address0 = zext_ln97_fu_655_p1;

assign out_r_0_address1 = zext_ln94_reg_992;

assign out_r_0_d0 = grp_fu_202_p_dout0;

assign out_r_0_d1 = grp_fu_194_p_dout0;

assign tmp_fu_462_p3 = ap_sig_allocacmp_n_9[32'd8];

assign zext_ln86_10_fu_597_p1 = i_7_reg_698;

assign zext_ln86_11_fu_602_p1 = i_8_reg_718;

assign zext_ln86_12_fu_612_p1 = i_9_reg_768;

assign zext_ln86_fu_607_p1 = i_reg_685;

assign zext_ln88_7_cast_fu_490_p3 = {{1'd1}, {i_7_fu_484_p2}};

assign zext_ln88_7_fu_498_p1 = zext_ln88_7_cast_fu_490_p3;

assign zext_ln88_8_cast_fu_520_p3 = {{1'd1}, {i_8_fu_514_p2}};

assign zext_ln88_8_fu_528_p1 = zext_ln88_8_cast_fu_520_p3;

assign zext_ln88_9_cast_fu_573_p3 = {{1'd1}, {i_9_fu_568_p2}};

assign zext_ln88_9_fu_581_p1 = zext_ln88_9_cast_fu_573_p3;

assign zext_ln88_cast_fu_555_p3 = {{1'd1}, {i_reg_685}};

assign zext_ln88_fu_562_p1 = zext_ln88_cast_fu_555_p3;

assign zext_ln94_fu_617_p1 = lshr_ln_reg_692_pp0_iter3_reg;

assign zext_ln97_1_cast_fu_622_p3 = {{1'd1}, {tmp_1_reg_713_pp0_iter4_reg}};

assign zext_ln97_1_fu_629_p1 = zext_ln97_1_cast_fu_622_p3;

assign zext_ln97_2_cast_fu_635_p3 = {{1'd1}, {tmp_2_reg_733_pp0_iter4_reg}};

assign zext_ln97_2_fu_642_p1 = zext_ln97_2_cast_fu_635_p3;

assign zext_ln97_3_cast_fu_661_p3 = {{1'd1}, {tmp_3_reg_783_pp0_iter4_reg}};

assign zext_ln97_3_fu_668_p1 = zext_ln97_3_cast_fu_661_p3;

assign zext_ln97_cast_fu_648_p3 = {{1'd1}, {lshr_ln_reg_692_pp0_iter4_reg}};

assign zext_ln97_fu_655_p1 = zext_ln97_cast_fu_648_p3;

always @ (posedge ap_clk) begin
    i_7_reg_698[0] <= 1'b1;
    i_8_reg_718[1] <= 1'b1;
    i_9_reg_768[1:0] <= 2'b11;
    zext_ln94_reg_992[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //FFT_fft_stage
